# permissions for end users to view kafkainstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkainstance-viewer-role
rules:
- apiGroups:
  - kafka.pmuir
  resources:
  - kafkainstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka.pmuir
  resources:
  - kafkainstances/status
  verbs:
  - get
