# permissions for end users to edit kafkainstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkainstance-editor-role
rules:
- apiGroups:
  - kafka.pmuir
  resources:
  - kafkainstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.pmuir
  resources:
  - kafkainstances/status
  verbs:
  - get
